---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  labels:
    app: flaskapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapi
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      initContainers:
        - name: init-upgrade
          image: flask-fyyur
          imagePullPolicy: Never

          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flaskapi-secrets
                  key: POSTGRES_PASSWORD
            
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: flaskapi-configmap
                  key: POSTGRES_USER

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: flaskapi-configmap
                  key: POSTGRES_DB

            - name: POSTGRES_SERVER
              valueFrom:
                configMapKeyRef:
                  name: flaskapi-configmap
                  key: POSTGRES_SERVER

            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: flaskapi-configmap
                  key: POSTGRES_PORT

      containers:
        - name: flaskapi
          image: flask-fyyur
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 60

          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flaskapi-secrets
                  key: POSTGRES_PASSWORD
            
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: flaskapi-configmap
                  key: POSTGRES_USER

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: flaskapi-configmap
                  key: POSTGRES_DB

            - name: POSTGRES_SERVER
              valueFrom:
                configMapKeyRef:
                  name: flaskapi-configmap
                  key: POSTGRES_SERVER

            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: flaskapi-configmap
                  key: POSTGRES_PORT

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flaskapi
  type: LoadBalancer