apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-job
spec:
  template:
    spec:
      containers:
      - name: migrate-job
        image: flask-fyyur
        command: ["flask",  "db", "migrate"]
      restartPolicy: Never
  backoffLimit: 4