"""empty message

Revision ID: fe592abffea5
Revises: e614b1a9b701
Create Date: 2021-12-11 18:06:24.010815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe592abffea5'
down_revision = 'e614b1a9b701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'vanue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Show', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Show', 'vanue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
